# See: https://github.com/ng-select/ng-select/blob/master/.github/workflows/release.yml
# [github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action)
name: Build and Deploy

on:
  push:
    tags:
      - v**

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GPAT: ${{ secrets.GPAT }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build:gh-pages

      - name: Deploy demo 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: ./dist/ng-project/browser/
